spring:
  application:
    name: ApiGatewayService
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: '8084'
eureka:
  client:
    enabled: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: '30'